# Generated by Django 4.1.2 on 2022-10-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('telegram_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, null=True)),
                ('number', models.CharField(max_length=11, null=True)),
            ],
        ),
    ]
