# Generated by Django 4.1.2 on 2022-10-22 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_week'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Week',
            new_name='Day',
        ),
    ]
