# Generated by Django 4.1.2 on 2022-10-23 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_day_day_week_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='clients.orderrequest'),
        ),
    ]
