# Generated by Django 4.1.2 on 2022-10-24 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_day_date_remove_orderrequest_day_day_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='date',
        ),
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='clients.day'),
        ),
    ]
