# Generated by Django 4.1.2 on 2022-10-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_day_orders_remove_orderrequest_date_day_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrequest',
            old_name='day',
            new_name='date',
        ),
    ]
