# Generated by Django 4.1.2 on 2022-10-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_rename_day_orderrequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='total_children',
        ),
    ]
